const WORDS=[
{word:"thra",cefr:"B1",ipa:"/θræ/",ce:"thra",sounds:-3,enDef:"Fake practice word.",jpWord:"（なし）",jpDef:"偽の単語",soundFile:"audio/thra.mp3",tallies:{hard:0,skip:0,easy:0}},

{word:"about",cefr:"A1",ipa:"/əˈbaʊt/",ce:"uh-bout",sounds:2,enDef:"Concerning or approximately.",jpWord:"約",jpDef:"およそ・だいたい",soundFile:"audio/about.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"accept",cefr:"A2",ipa:"/əkˈsɛpt/",ce:"uh-ksept",sounds:3,enDef:"To agree or receive.",jpWord:"受け入れる",jpDef:"承認する・受け取る",soundFile:"audio/accept.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"accident",cefr:"A2",ipa:"/ˈæksɪdənt/",ce:"aks-i-dent",sounds:4,enDef:"An unexpected event.",jpWord:"事故",jpDef:"予期せぬ出来事",soundFile:"audio/accident.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"acknowledge",cefr:"B1",ipa:"/əkˈnɒlɪdʒ/",ce:"uh-nol-ij",sounds:3,enDef:"To admit or recognize.",jpWord:"認める",jpDef:"存在や事実を認める",soundFile:"audio/acknowledge.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"act",cefr:"A1",ipa:"/ækt/",ce:"akt",sounds:3,enDef:"To do something.",jpWord:"行動する",jpDef:"何かをする",soundFile:"audio/act.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"add",cefr:"A1",ipa:"/æd/",ce:"ad",sounds:2,enDef:"To put together.",jpWord:"足す",jpDef:"数や量を増やす",soundFile:"audio/add.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"added",cefr:"A2",ipa:"/ˈædɪd/",ce:"ad-id",sounds:3,enDef:"Past of add.",jpWord:"足した",jpDef:"追加した",soundFile:"audio/added.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ago",cefr:"A1",ipa:"/əˈɡoʊ/",ce:"uh-go",sounds:2,enDef:"In the past.",jpWord:"前に",jpDef:"過去の時点を表す",soundFile:"audio/ago.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ahead",cefr:"A2",ipa:"/əˈhɛd/",ce:"uh-hed",sounds:2,enDef:"In front.",jpWord:"前に",jpDef:"前方に",soundFile:"audio/ahead.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"aisle",cefr:"B1",ipa:"/aɪl/",ce:"ile",sounds:1,enDef:"A passage between seats.",jpWord:"通路",jpDef:"列の間の通り道",soundFile:"audio/aisle.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"all",cefr:"A1",ipa:"/ɔːl/",ce:"awl",sounds:1,enDef:"The whole amount.",jpWord:"すべて",jpDef:"全部",soundFile:"audio/all.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"although",cefr:"B1",ipa:"/ɔːlˈðoʊ/",ce:"awl-tho",sounds:2,enDef:"Even though.",jpWord:"〜だけれども",jpDef:"譲歩を表す接続詞",soundFile:"audio/although.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"analysis",cefr:"B2",ipa:"/əˈnæləsɪs/",ce:"uh-nal-uh-sis",sounds:4,enDef:"Detailed examination.",jpWord:"分析",jpDef:"詳しく調べること",soundFile:"audio/analysis.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"angle",cefr:"B1",ipa:"/ˈæŋɡəl/",ce:"ang-gul",sounds:3,enDef:"A shape made by two lines.",jpWord:"角度",jpDef:"線が作る角",soundFile:"audio/angle.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"angry",cefr:"A2",ipa:"/ˈæŋɡri/",ce:"ang-gree",sounds:3,enDef:"Feeling strong displeasure.",jpWord:"怒っている",jpDef:"腹を立てている",soundFile:"audio/angry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"anguish",cefr:"B2",ipa:"/ˈæŋɡwɪʃ/",ce:"ang-gwish",sounds:2,enDef:"Severe mental pain.",jpWord:"苦悩",jpDef:"強い精神的苦痛",soundFile:"audio/anguish.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"animal",cefr:"A1",ipa:"/ˈænɪməl/",ce:"an-i-mul",sounds:3,enDef:"A living creature.",jpWord:"動物",jpDef:"生き物",soundFile:"audio/animal.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"answer",cefr:"A1",ipa:"/ˈænsər/",ce:"an-ser",sounds:2,enDef:"A response.",jpWord:"答え",jpDef:"返事",soundFile:"audio/answer.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"anxious",cefr:"B1",ipa:"/ˈæŋkʃəs/",ce:"ank-shus",sounds:2,enDef:"Feeling worried.",jpWord:"不安な",jpDef:"心配している",soundFile:"audio/anxious.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"antique",cefr:"B1",ipa:"/ænˈtiːk/",ce:"an-teek",sounds:2,enDef:"Very old and valuable.",jpWord:"骨董品",jpDef:"古くて価値のある物",soundFile:"audio/antique.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"apple",cefr:"A1",ipa:"/ˈæpəl/",ce:"ap-ul",sounds:2,enDef:"A round fruit.",jpWord:"りんご",jpDef:"丸い果物",soundFile:"audio/apple.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"apply",cefr:"A2",ipa:"/əˈplaɪ/",ce:"uh-ply",sounds:2,enDef:"To make a request.",jpWord:"申し込む",jpDef:"申請する",soundFile:"audio/apply.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ask",cefr:"A1",ipa:"/æsk/",ce:"ask",sounds:3,enDef:"To request information.",jpWord:"尋ねる",jpDef:"質問する",soundFile:"audio/ask.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"asked",cefr:"A1",ipa:"/æskt/",ce:"askt",sounds:4,enDef:"Past of ask.",jpWord:"尋ねた",jpDef:"質問した",soundFile:"audio/asked.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"author",cefr:"B1",ipa:"/ˈɔːθər/",ce:"aw-thur",sounds:2,enDef:"A person who writes books.",jpWord:"著者",jpDef:"本を書く人",soundFile:"audio/author.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"autumn",cefr:"A2",ipa:"/ˈɔːtəm/",ce:"aw-tum",sounds:2,enDef:"The season after summer.",jpWord:"秋",jpDef:"夏の次の季節",soundFile:"audio/autumn.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"baby",cefr:"A1",ipa:"/ˈbeɪbi/",ce:"bay-bee",sounds:2,enDef:"A very young child.",jpWord:"赤ちゃん",jpDef:"生まれたばかりの子",soundFile:"audio/baby.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"back",cefr:"A1",ipa:"/bæk/",ce:"bak",sounds:3,enDef:"The rear part.",jpWord:"背中",jpDef:"後ろ側",soundFile:"audio/back.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"badge",cefr:"A2",ipa:"/bædʒ/",ce:"baj",sounds:2,enDef:"A small sign or symbol.",jpWord:"バッジ",jpDef:"小さな記章",soundFile:"audio/badge.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bake",cefr:"A2",ipa:"/beɪk/",ce:"bayk",sounds:2,enDef:"To cook with dry heat.",jpWord:"焼く",jpDef:"オーブンで調理する",soundFile:"audio/bake.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bank",cefr:"A1",ipa:"/bæŋk/",ce:"bank",sounds:4,enDef:"A place to keep money.",jpWord:"銀行",jpDef:"お金を預ける場所",soundFile:"audio/bank.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"basic",cefr:"A2",ipa:"/ˈbeɪsɪk/",ce:"bay-sik",sounds:3,enDef:"Simple and essential.",jpWord:"基本的な",jpDef:"基礎的な",soundFile:"audio/basic.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bat",cefr:"A1",ipa:"/bæt/",ce:"bat",sounds:3,enDef:"A flying mammal.",jpWord:"コウモリ",jpDef:"夜に飛ぶ動物",soundFile:"audio/bat.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bees",cefr:"A1",ipa:"/biːz/",ce:"beez",sounds:2,enDef:"Flying insects that make honey.",jpWord:"ミツバチ",jpDef:"蜂の一種",soundFile:"audio/bees.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"beige",cefr:"B1",ipa:"/beɪʒ/",ce:"bayzh",sounds:2,enDef:"A light brown color.",jpWord:"ベージュ",jpDef:"薄茶色",soundFile:"audio/beige.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"behind",cefr:"A1",ipa:"/bɪˈhaɪnd/",ce:"bi-hind",sounds:2,enDef:"At the back of.",jpWord:"〜の後ろ",jpDef:"後ろ側に",soundFile:"audio/behind.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"belief",cefr:"B1",ipa:"/bɪˈliːf/",ce:"bi-leef",sounds:2,enDef:"Something you accept as true.",jpWord:"信念",jpDef:"信じている考え",soundFile:"audio/belief.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"berry",cefr:"A2",ipa:"/ˈbɛri/",ce:"ber-ee",sounds:2,enDef:"A small juicy fruit.",jpWord:"ベリー",jpDef:"小さな果実",soundFile:"audio/berry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"better",cefr:"A1",ipa:"/ˈbɛtər/",ce:"bet-er",sounds:2,enDef:"More good.",jpWord:"より良い",jpDef:"より良い状態",soundFile:"audio/better.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bird",cefr:"A1",ipa:"/bɝːd/",ce:"berd",sounds:1,enDef:"A flying animal with feathers.",jpWord:"鳥",jpDef:"羽のある飛ぶ動物",soundFile:"audio/bird.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"blitz",cefr:"B2",ipa:"/blɪts/",ce:"blits",sounds:4,enDef:"A sudden intense attack.",jpWord:"電撃作戦",jpDef:"短時間の激しい攻撃",soundFile:"audio/blitz.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"blood",cefr:"A2",ipa:"/blʌd/",ce:"blud",sounds:3,enDef:"Red liquid in the body.",jpWord:"血",jpDef:"体内を流れる赤い液体",soundFile:"audio/blood.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"boat",cefr:"A1",ipa:"/boʊt/",ce:"boht",sounds:2,enDef:"A small vehicle for water.",jpWord:"ボート",jpDef:"水上の乗り物",soundFile:"audio/boat.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bold",cefr:"B1",ipa:"/boʊld/",ce:"bohld",sounds:3,enDef:"Brave or strong in appearance.",jpWord:"大胆な",jpDef:"勇敢な・目立つ",soundFile:"audio/bold.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"book",cefr:"A1",ipa:"/bʊk/",ce:"buk",sounds:2,enDef:"A written story or information.",jpWord:"本",jpDef:"文字が書かれた冊子",soundFile:"audio/book.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"born",cefr:"A1",ipa:"/bɔːrn/",ce:"born",sounds:3,enDef:"Brought into life.",jpWord:"生まれた",jpDef:"生まれた状態",soundFile:"audio/born.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"box",cefr:"A1",ipa:"/bɑks/",ce:"boks",sounds:3,enDef:"A container.",jpWord:"箱",jpDef:"物を入れる容器",soundFile:"audio/box.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"boy",cefr:"A1",ipa:"/bɔɪ/",ce:"boy",sounds:2,enDef:"A male child.",jpWord:"男の子",jpDef:"少年",soundFile:"audio/boy.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bread",cefr:"A1",ipa:"/brɛd/",ce:"bred",sounds:4,enDef:"A baked food made from flour.",jpWord:"パン",jpDef:"小麦粉で作る主食",soundFile:"audio/bread.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"break",cefr:"A1",ipa:"/breɪk/",ce:"brayk",sounds:4,enDef:"To separate into pieces.",jpWord:"壊す",jpDef:"割る・壊れる",soundFile:"audio/break.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bridge",cefr:"A1",ipa:"/brɪdʒ/",ce:"brij",sounds:4,enDef:"A structure over water or roads.",jpWord:"橋",jpDef:"川や道に架かる構造物",soundFile:"audio/bridge.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"build",cefr:"A1",ipa:"/bɪld/",ce:"bild",sounds:4,enDef:"To make or construct.",jpWord:"建てる",jpDef:"作る・建設する",soundFile:"audio/build.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bubble",cefr:"A1",ipa:"/ˈbʌbəl/",ce:"bub-ul",sounds:3,enDef:"A ball of air in liquid.",jpWord:"泡",jpDef:"液体中の空気の玉",soundFile:"audio/bubble.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"burn",cefr:"A1",ipa:"/bɝːn/",ce:"bern",sounds:2,enDef:"To be damaged by fire.",jpWord:"燃える",jpDef:"火で傷つく",soundFile:"audio/burn.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"bus",cefr:"A1",ipa:"/bʌs/",ce:"bus",sounds:3,enDef:"A large public vehicle.",jpWord:"バス",jpDef:"大きな公共交通機関",soundFile:"audio/bus.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"buses",cefr:"A1",ipa:"/ˈbʌsɪz/",ce:"bus-iz",sounds:4,enDef:"Plural of bus.",jpWord:"バス（複数）",jpDef:"バスの複数形",soundFile:"audio/buses.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"butcher",cefr:"A2",ipa:"/ˈbʊtʃər/",ce:"buch-er",sounds:3,enDef:"A person who sells meat.",jpWord:"肉屋",jpDef:"肉を売る人",soundFile:"audio/butcher.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"butter",cefr:"A1",ipa:"/ˈbʌtər/",ce:"but-er",sounds:2,enDef:"A yellow dairy food.",jpWord:"バター",jpDef:"乳製品",soundFile:"audio/butter.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"buzz",cefr:"A2",ipa:"/bʌz/",ce:"buz",sounds:3,enDef:"A low humming sound.",jpWord:"ブーン",jpDef:"低い振動音",soundFile:"audio/buzz.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cake",cefr:"A1",ipa:"/keɪk/",ce:"kayk",sounds:2,enDef:"A baked sweet dessert.",jpWord:"ケーキ",jpDef:"甘い焼き菓子",soundFile:"audio/cake.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"calf",cefr:"B1",ipa:"/kæf/",ce:"kaf",sounds:3,enDef:"A young cow.",jpWord:"子牛",jpDef:"若い牛",soundFile:"audio/calf.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"called",cefr:"A1",ipa:"/kɔːld/",ce:"kawld",sounds:3,enDef:"Past of call.",jpWord:"呼んだ",jpDef:"呼びかけた",soundFile:"audio/called.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"candy",cefr:"A1",ipa:"/ˈkændi/",ce:"kan-dee",sounds:2,enDef:"Sweet food made of sugar.",jpWord:"キャンディ",jpDef:"砂糖のお菓子",soundFile:"audio/candy.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"captain",cefr:"A2",ipa:"/ˈkæptɪn/",ce:"kap-tin",sounds:3,enDef:"Leader of a team or ship.",jpWord:"船長",jpDef:"責任者・リーダー",soundFile:"audio/captain.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"car",cefr:"A1",ipa:"/kɑːr/",ce:"kar",sounds:2,enDef:"A vehicle with four wheels.",jpWord:"車",jpDef:"四輪の乗り物",soundFile:"audio/car.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"carry",cefr:"A1",ipa:"/ˈkæri/",ce:"kar-ee",sounds:2,enDef:"To hold and move.",jpWord:"運ぶ",jpDef:"持って運ぶ",soundFile:"audio/carry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cars",cefr:"A1",ipa:"/kɑːrz/",ce:"karz",sounds:3,enDef:"Plural of car.",jpWord:"車（複数）",jpDef:"車の複数形",soundFile:"audio/cars.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"castle",cefr:"A1",ipa:"/ˈkæsəl/",ce:"kas-ul",sounds:3,enDef:"A large stone building.",jpWord:"城",jpDef:"石でできた大きな建物",soundFile:"audio/castle.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cat",cefr:"A1",ipa:"/kæt/",ce:"kat",sounds:3,enDef:"A small animal.",jpWord:"猫",jpDef:"小さな動物",soundFile:"audio/cat.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cats",cefr:"A1",ipa:"/kæts/",ce:"kats",sounds:4,enDef:"Plural of cat.",jpWord:"猫（複数）",jpDef:"猫の複数形",soundFile:"audio/cats.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ceiling",cefr:"A1",ipa:"/ˈsiːlɪŋ/",ce:"see-ling",sounds:2,enDef:"The top inside surface of a room.",jpWord:"天井",jpDef:"部屋の上の内側",soundFile:"audio/ceiling.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"center",cefr:"A1",ipa:"/ˈsɛntər/",ce:"sen-ter",sounds:2,enDef:"The middle of something.",jpWord:"中心",jpDef:"真ん中",soundFile:"audio/center.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"chair",cefr:"A1",ipa:"/tʃɛr/",ce:"chair",sounds:3,enDef:"A seat for one person.",jpWord:"椅子",jpDef:"座るための家具",soundFile:"audio/chair.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"chef",cefr:"A1",ipa:"/ʃɛf/",ce:"shef",sounds:3,enDef:"A professional cook.",jpWord:"シェフ",jpDef:"料理人",soundFile:"audio/chef.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"character",cefr:"A2",ipa:"/ˈkærəktər/",ce:"kar-uhk-ter",sounds:4,enDef:"A person in a story.",jpWord:"登場人物",jpDef:"物語の人物",soundFile:"audio/character.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"chaos",cefr:"B2",ipa:"/ˈkeɪɒs/",ce:"kay-os",sounds:2,enDef:"Complete disorder.",jpWord:"混沌",jpDef:"無秩序な状態",soundFile:"audio/chaos.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"chief",cefr:"A2",ipa:"/tʃiːf/",ce:"cheef",sounds:2,enDef:"The leader of a group.",jpWord:"長",jpDef:"リーダー",soundFile:"audio/chief.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"church",cefr:"A1",ipa:"/tʃɜːrtʃ/",ce:"church",sounds:3,enDef:"A building for Christian worship.",jpWord:"教会",jpDef:"キリスト教の礼拝堂",soundFile:"audio/church.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"city",cefr:"A1",ipa:"/ˈsɪti/",ce:"siti",sounds:2,enDef:"A large town.",jpWord:"都市",jpDef:"大きな町",soundFile:"audio/city.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cleaned",cefr:"A1",ipa:"/kliːnd/",ce:"kleend",sounds:3,enDef:"Made something clean.",jpWord:"掃除した",jpDef:"きれいにした",soundFile:"audio/cleaned.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"clock",cefr:"A1",ipa:"/klɒk/",ce:"klok",sounds:4,enDef:"A device that tells time.",jpWord:"時計",jpDef:"時間を示す機械",soundFile:"audio/clock.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"coffee",cefr:"A1",ipa:"/ˈkɔːfi/",ce:"kawfee",sounds:3,enDef:"A hot drink made from beans.",jpWord:"コーヒー",jpDef:"豆から作る飲み物",soundFile:"audio/coffee.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cold",cefr:"A1",ipa:"/koʊld/",ce:"kohld",sounds:3,enDef:"Low temperature.",jpWord:"寒い",jpDef:"気温が低い",soundFile:"audio/cold.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"coin",cefr:"A1",ipa:"/kɔɪn/",ce:"koin",sounds:2,enDef:"A small piece of metal money.",jpWord:"硬貨",jpDef:"金属のお金",soundFile:"audio/coin.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"colonel",cefr:"B1",ipa:"/ˈkɜːrnəl/",ce:"kernel",sounds:2,enDef:"A high army officer.",jpWord:"大佐",jpDef:"軍の高位の将校",soundFile:"audio/colonel.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"comb",cefr:"A1",ipa:"/koʊm/",ce:"kohm",sounds:2,enDef:"A tool for hair.",jpWord:"くし",jpDef:"髪をとかす道具",soundFile:"audio/comb.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"come",cefr:"A1",ipa:"/kʌm/",ce:"kum",sounds:2,enDef:"To move toward someone.",jpWord:"来る",jpDef:"近づく",soundFile:"audio/come.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"column",cefr:"B1",ipa:"/ˈkɒləm/",ce:"kolum",sounds:3,enDef:"A vertical pillar.",jpWord:"柱",jpDef:"縦の支柱",soundFile:"audio/column.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"corps",cefr:"B2",ipa:"/kɔːr/",ce:"kor",sounds:1,enDef:"A military group.",jpWord:"軍団",jpDef:"軍の部隊",soundFile:"audio/corps.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cough",cefr:"A2",ipa:"/kɒf/",ce:"kof",sounds:2,enDef:"To make a sharp throat sound.",jpWord:"咳",jpDef:"せきをする",soundFile:"audio/cough.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"country",cefr:"A1",ipa:"/ˈkʌntri/",ce:"kun-tree",sounds:4,enDef:"A nation.",jpWord:"国",jpDef:"国家",soundFile:"audio/country.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cow",cefr:"A1",ipa:"/kaʊ/",ce:"kow",sounds:1,enDef:"A farm animal that gives milk.",jpWord:"牛",jpDef:"乳を出す動物",soundFile:"audio/cow.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"crescendo",cefr:"B2",ipa:"/krəˈʃɛndoʊ/",ce:"kruh-shen-doh",sounds:5,enDef:"A gradual increase in loudness.",jpWord:"クレッシェンド",jpDef:"音がだんだん大きくなること",soundFile:"audio/crescendo.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"critique",cefr:"B2",ipa:"/krɪˈtiːk/",ce:"kri-teek",sounds:3,enDef:"A detailed review.",jpWord:"批評",jpDef:"詳しい評価",soundFile:"audio/critique.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cry",cefr:"A1",ipa:"/kraɪ/",ce:"kry",sounds:2,enDef:"To shed tears.",jpWord:"泣く",jpDef:"涙を流す",soundFile:"audio/cry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cup",cefr:"A1",ipa:"/kʌp/",ce:"kup",sounds:2,enDef:"A small drinking container.",jpWord:"カップ",jpDef:"飲み物の容器",soundFile:"audio/cup.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cupboard",cefr:"A2",ipa:"/ˈkʌbərd/",ce:"kub-erd",sounds:3,enDef:"A cabinet for storage.",jpWord:"食器棚",jpDef:"物を入れる棚",soundFile:"audio/cupboard.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cycle",cefr:"A2",ipa:"/ˈsaɪkəl/",ce:"sy-kul",sounds:3,enDef:"To ride a bicycle.",jpWord:"自転車に乗る",jpDef:"自転車で移動する",soundFile:"audio/cycle.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"debris",cefr:"B2",ipa:"/ˈdeɪbriː/",ce:"day-bree",sounds:2,enDef:"Scattered broken pieces.",jpWord:"がれき",jpDef:"壊れた破片",soundFile:"audio/debris.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"day",cefr:"A1",ipa:"/deɪ/",ce:"day",sounds:1,enDef:"A 24-hour period.",jpWord:"日",jpDef:"一日",soundFile:"audio/day.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"debt",cefr:"B1",ipa:"/dɛt/",ce:"det",sounds:2,enDef:"Money owed.",jpWord:"借金",jpDef:"返すべきお金",soundFile:"audio/debt.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"decision",cefr:"B1",ipa:"/dɪˈsɪʒən/",ce:"di-sizh-un",sounds:4,enDef:"A choice.",jpWord:"決定",jpDef:"選択",soundFile:"audio/decision.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"déjà vu",cefr:"B2",ipa:"/ˌdeɪʒɑː ˈvuː/",ce:"day-zhah voo",sounds:4,enDef:"Feeling that something is familiar.",jpWord:"デジャヴ",jpDef:"既視感",soundFile:"audio/dejavu.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"design",cefr:"A2",ipa:"/dɪˈzaɪn/",ce:"di-zine",sounds:3,enDef:"To plan how something looks.",jpWord:"設計",jpDef:"形を考えること",soundFile:"audio/design.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"diaphragm",cefr:"B2",ipa:"/ˈdaɪəfræm/",ce:"dye-uh-fram",sounds:4,enDef:"A muscle used for breathing.",jpWord:"横隔膜",jpDef:"呼吸に使う筋肉",soundFile:"audio/diaphragm.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"dinner",cefr:"A1",ipa:"/ˈdɪnər/",ce:"din-er",sounds:3,enDef:"The main evening meal.",jpWord:"夕食",jpDef:"夜の食事",soundFile:"audio/dinner.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"do",cefr:"A1",ipa:"/duː/",ce:"doo",sounds:1,enDef:"To perform an action.",jpWord:"する",jpDef:"行う",soundFile:"audio/do.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"dog",cefr:"A1",ipa:"/dɔːg/",ce:"dawg",sounds:2,enDef:"A common pet animal.",jpWord:"犬",jpDef:"ペットの動物",soundFile:"audio/dog.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"dogs",cefr:"A1",ipa:"/dɔːgz/",ce:"dawgz",sounds:3,enDef:"More than one dog.",jpWord:"犬たち",jpDef:"複数の犬",soundFile:"audio/dogs.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"dough",cefr:"A2",ipa:"/doʊ/",ce:"doh",sounds:1,enDef:"Unbaked bread mixture.",jpWord:"生地",jpDef:"パンの生地",soundFile:"audio/dough.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"doubt",cefr:"A2",ipa:"/daʊt/",ce:"dowt",sounds:3,enDef:"To feel uncertain.",jpWord:"疑う",jpDef:"確信がない",soundFile:"audio/doubt.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"draw",cefr:"A1",ipa:"/drɔː/",ce:"draw",sounds:2,enDef:"To make a picture.",jpWord:"描く",jpDef:"絵をかく",soundFile:"audio/draw.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"dry",cefr:"A1",ipa:"/draɪ/",ce:"dry",sounds:2,enDef:"Not wet.",jpWord:"乾いた",jpDef:"濡れていない",soundFile:"audio/dry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"eat",cefr:"A1",ipa:"/iːt/",ce:"eet",sounds:1,enDef:"To put food in your mouth.",jpWord:"食べる",jpDef:"食事をする",soundFile:"audio/eat.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"edge",cefr:"A1",ipa:"/ɛdʒ/",ce:"ej",sounds:2,enDef:"The side of something.",jpWord:"縁",jpDef:"端",soundFile:"audio/edge.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"educate",cefr:"B1",ipa:"/ˈɛdʒukeɪt/",ce:"ej-uh-kate",sounds:5,enDef:"To teach.",jpWord:"教育する",jpDef:"教える",soundFile:"audio/educate.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"eight",cefr:"A1",ipa:"/eɪt/",ce:"ayt",sounds:1,enDef:"The number 8.",jpWord:"八",jpDef:"数字の8",soundFile:"audio/eight.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"either",cefr:"A2",ipa:"/ˈiːðər/",ce:"ee-ther",sounds:3,enDef:"One or the other.",jpWord:"どちらか",jpDef:"二つのうち一つ",soundFile:"audio/either.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"em",cefr:"B2",ipa:"/ɛm/",ce:"em",sounds:1,enDef:"A printing unit of width.",jpWord:"全角",jpDef:"印刷の単位",soundFile:"audio/'em.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"enemy",cefr:"A2",ipa:"/ˈɛnəmi/",ce:"en-uh-mee",sounds:4,enDef:"Someone who opposes you.",jpWord:"敵",jpDef:"対立する人",soundFile:"audio/enemy.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"enjoy",cefr:"A1",ipa:"/ɪnˈdʒɔɪ/",ce:"en-joy",sounds:3,enDef:"To like something.",jpWord:"楽しむ",jpDef:"喜ぶ",soundFile:"audio/enjoy.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"envelope",cefr:"A2",ipa:"/ˈɛnvəloʊp/",ce:"en-vuh-lohp",sounds:4,enDef:"A paper container for letters.",jpWord:"封筒",jpDef:"手紙を入れる紙",soundFile:"audio/envelope.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"equal",cefr:"A2",ipa:"/ˈiːkwəl/",ce:"ee-kwul",sounds:3,enDef:"The same in value.",jpWord:"等しい",jpDef:"同じ",soundFile:"audio/equal.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"er",cefr:"B2",ipa:"/ɜːr/",ce:"er",sounds:1,enDef:"A hesitation sound.",jpWord:"えー",jpDef:"言いよどみ",soundFile:"audio/'er.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"Europe",cefr:"A1",ipa:"/ˈjʊərəp/",ce:"yur-uhp",sounds:4,enDef:"A continent.",jpWord:"ヨーロッパ",jpDef:"大陸",soundFile:"audio/europe.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"exam",cefr:"A1",ipa:"/ɪɡˈzæm/",ce:"ig-zam",sounds:3,enDef:"A test.",jpWord:"試験",jpDef:"テスト",soundFile:"audio/exam.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"exact",cefr:"A2",ipa:"/ɪɡˈzækt/",ce:"ig-zakt",sounds:4,enDef:"Completely correct.",jpWord:"正確な",jpDef:"間違いのない",soundFile:"audio/exact.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"exist",cefr:"B1",ipa:"/ɪɡˈzɪst/",ce:"ig-zist",sounds:4,enDef:"To be real.",jpWord:"存在する",jpDef:"実在する",soundFile:"audio/exist.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"fascinate",cefr:"B2",ipa:"/ˈfæsɪneɪt/",ce:"fas-ih-nate",sounds:5,enDef:"To strongly interest.",jpWord:"魅了する",jpDef:"強く惹きつける",soundFile:"audio/fascinate.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"facial",cefr:"B1",ipa:"/ˈfeɪʃəl/",ce:"fay-shul",sounds:3,enDef:"Related to the face.",jpWord:"顔の",jpDef:"顔に関する",soundFile:"audio/facial.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"fact",cefr:"A1",ipa:"/fækt/",ce:"fakt",sounds:4,enDef:"Something true.",jpWord:"事実",jpDef:"真実",soundFile:"audio/fact.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"fan",cefr:"A1",ipa:"/fæn/",ce:"fan",sounds:2,enDef:"A device that moves air.",jpWord:"扇風機",jpDef:"風を送る機械",soundFile:"audio/fan.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"father",cefr:"A1",ipa:"/ˈfɑːðər/",ce:"fah-ther",sounds:3,enDef:"A male parent.",jpWord:"父",jpDef:"お父さん",soundFile:"audio/father.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"feud",cefr:"B2",ipa:"/fjuːd/",ce:"fyood",sounds:2,enDef:"A long conflict.",jpWord:"確執",jpDef:"長い争い",soundFile:"audio/feud.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"few",cefr:"A1",ipa:"/fjuː/",ce:"fyoo",sounds:2,enDef:"Not many.",jpWord:"少しの",jpDef:"わずかな",soundFile:"audio/few.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"field",cefr:"A1",ipa:"/fiːld/",ce:"feeld",sounds:3,enDef:"An open area of land.",jpWord:"畑",jpDef:"野原",soundFile:"audio/field.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"fifth",cefr:"A1",ipa:"/fɪfθ/",ce:"fifth",sounds:4,enDef:"Number five in order.",jpWord:"第五",jpDef:"5番目",soundFile:"audio/fifth.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"finger",cefr:"A1",ipa:"/ˈfɪŋɡər/",ce:"fing-ger",sounds:4,enDef:"A part of your hand.",jpWord:"指",jpDef:"手の一部",soundFile:"audio/finger.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"first",cefr:"A1",ipa:"/fɜːrst/",ce:"furst",sounds:4,enDef:"Before all others.",jpWord:"最初",jpDef:"一番目",soundFile:"audio/first.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"flaccid",cefr:"B2",ipa:"/ˈflæsɪd/",ce:"flas-id",sounds:4,enDef:"Soft or weak.",jpWord:"たるんだ",jpDef:"力のない",soundFile:"audio/flaccid.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"flood",cefr:"A2",ipa:"/flʌd/",ce:"flud",sounds:3,enDef:"A large amount of water.",jpWord:"洪水",jpDef:"大水",soundFile:"audio/flood.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"fly",cefr:"A1",ipa:"/flaɪ/",ce:"fly",sounds:2,enDef:"To move through air.",jpWord:"飛ぶ",jpDef:"空を移動する",soundFile:"audio/fly.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"for",cefr:"A1",ipa:"/fɔːr/",ce:"for",sounds:1,enDef:"Used to show purpose.",jpWord:"〜のために",jpDef:"目的を示す",soundFile:"audio/for.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"foreign",cefr:"A2",ipa:"/ˈfɒrən/",ce:"for-in",sounds:3,enDef:"From another country.",jpWord:"外国の",jpDef:"海外の",soundFile:"audio/foreign.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"fork",cefr:"A1",ipa:"/fɔːrk/",ce:"fork",sounds:4,enDef:"A tool for eating.",jpWord:"フォーク",jpDef:"食器",soundFile:"audio/fork.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"friend",cefr:"A1",ipa:"/frɛnd/",ce:"frend",sounds:4,enDef:"Someone you like.",jpWord:"友達",jpDef:"仲の良い人",soundFile:"audio/friend.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"full",cefr:"A1",ipa:"/fʊl/",ce:"fool",sounds:2,enDef:"Not empty.",jpWord:"いっぱい",jpDef:"満たされている",soundFile:"audio/full.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"future",cefr:"A1",ipa:"/ˈfjuːtʃər/",ce:"fyoo-cher",sounds:4,enDef:"Time that is coming.",jpWord:"未来",jpDef:"これからの時間",soundFile:"audio/future.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"game",cefr:"A1",ipa:"/ɡeɪm/",ce:"game",sounds:2,enDef:"Something you play.",jpWord:"ゲーム",jpDef:"遊び",soundFile:"audio/game.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"gem",cefr:"B1",ipa:"/dʒɛm/",ce:"jem",sounds:2,enDef:"A precious stone.",jpWord:"宝石",jpDef:"貴石",soundFile:"audio/gem.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"genre",cefr:"B2",ipa:"/ˈʒɑːnrə/",ce:"zhawn-ruh",sounds:3,enDef:"A type of art or music.",jpWord:"ジャンル",jpDef:"種類",soundFile:"audio/genre.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"get",cefr:"A1",ipa:"/ɡɛt/",ce:"get",sounds:3,enDef:"To receive or obtain.",jpWord:"得る",jpDef:"手に入れる",soundFile:"audio/get.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ghetto",cefr:"B2",ipa:"/ˈɡɛtoʊ/",ce:"get-oh",sounds:3,enDef:"A poor urban area.",jpWord:"ゲットー",jpDef:"貧困地区",soundFile:"audio/ghetto.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ghost",cefr:"A2",ipa:"/ɡoʊst/",ce:"gohst",sounds:2,enDef:"The spirit of a dead person.",jpWord:"幽霊",jpDef:"死者の霊",soundFile:"audio/ghost.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ghastly",cefr:"B2",ipa:"/ˈɡæstli/",ce:"gast-lee",sounds:4,enDef:"Very shocking or horrible.",jpWord:"ぞっとする",jpDef:"恐ろしい",soundFile:"audio/ghastly.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"giant",cefr:"A2",ipa:"/ˈdʒaɪənt/",ce:"jy-unt",sounds:3,enDef:"Very large.",jpWord:"巨大な",jpDef:"とても大きい",soundFile:"audio/giant.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"give",cefr:"A1",ipa:"/ɡɪv/",ce:"giv",sounds:3,enDef:"To hand something to someone.",jpWord:"あげる",jpDef:"渡す",soundFile:"audio/give.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"gnome",cefr:"B1",ipa:"/noʊm/",ce:"nohm",sounds:1,enDef:"A small mythical creature.",jpWord:"ノーム",jpDef:"小さな妖精",soundFile:"audio/gnome.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"go",cefr:"A1",ipa:"/ɡoʊ/",ce:"goh",sounds:1,enDef:"To move somewhere.",jpWord:"行く",jpDef:"移動する",soundFile:"audio/go.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"graph",cefr:"A2",ipa:"/ɡræf/",ce:"graf",sounds:4,enDef:"A visual representation of data.",jpWord:"グラフ",jpDef:"図表",soundFile:"audio/graph.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"grandfather",cefr:"A1",ipa:"/ˈɡrændˌfɑːðər/",ce:"grand-fah-ther",sounds:7,enDef:"Your parent's father.",jpWord:"祖父",jpDef:"おじいさん",soundFile:"audio/grandfather.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"gradual",cefr:"B1",ipa:"/ˈɡrædʒuəl/",ce:"graj-oo-uhl",sounds:5,enDef:"Happening slowly.",jpWord:"徐々の",jpDef:"ゆっくり進む",soundFile:"audio/gradual.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"grey",cefr:"A1",ipa:"/ɡreɪ/",ce:"gray",sounds:1,enDef:"A color between black and white.",jpWord:"灰色",jpDef:"グレー",soundFile:"audio/grey.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"grow",cefr:"A1",ipa:"/ɡroʊ/",ce:"groh",sounds:2,enDef:"To become bigger.",jpWord:"育つ",jpDef:"大きくなる",soundFile:"audio/grow.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"guess",cefr:"A1",ipa:"/ɡɛs/",ce:"ges",sounds:3,enDef:"To make a prediction.",jpWord:"推測する",jpDef:"当てる",soundFile:"audio/guess.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"guide",cefr:"A1",ipa:"/ɡaɪd/",ce:"gyd",sounds:2,enDef:"To show the way.",jpWord:"案内する",jpDef:"導く",soundFile:"audio/guide.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"guilt",cefr:"B1",ipa:"/ɡɪlt/",ce:"gilt",sounds:4,enDef:"Feeling of doing wrong.",jpWord:"罪悪感",jpDef:"悪いと思う気持ち",soundFile:"audio/guilt.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"guitar",cefr:"A1",ipa:"/ɡɪˈtɑːr/",ce:"gi-tar",sounds:4,enDef:"A musical instrument.",jpWord:"ギター",jpDef:"弦楽器",soundFile:"audio/guitar.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"gun",cefr:"A1",ipa:"/ɡʌn/",ce:"gun",sounds:2,enDef:"A weapon that fires bullets.",jpWord:"銃",jpDef:"弾を撃つ武器",soundFile:"audio/gun.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"gym",cefr:"A1",ipa:"/dʒɪm/",ce:"jim",sounds:2,enDef:"A place to exercise.",jpWord:"ジム",jpDef:"運動する場所",soundFile:"audio/gym.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"hand",cefr:"A1",ipa:"/hænd/",ce:"hand",sounds:3,enDef:"Part of your arm.",jpWord:"手",jpDef:"体の一部",soundFile:"audio/hand.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"handkerchief",cefr:"B2",ipa:"/ˈhæŋkərtʃɪf/",ce:"hang-ker-chif",sounds:7,enDef:"A small cloth for wiping.",jpWord:"ハンカチ",jpDef:"小さな布",soundFile:"audio/handkerchief.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"happy",cefr:"A1",ipa:"/ˈhæpi/",ce:"hap-ee",sounds:3,enDef:"Feeling good.",jpWord:"幸せ",jpDef:"うれしい",soundFile:"audio/happy.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"hard",cefr:"A1",ipa:"/hɑːrd/",ce:"hard",sounds:3,enDef:"Not soft.",jpWord:"硬い",jpDef:"固い",soundFile:"audio/hard.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"harmony",cefr:"B1",ipa:"/ˈhɑːrməni/",ce:"har-muh-nee",sounds:6,enDef:"Pleasant combination.",jpWord:"調和",jpDef:"バランス",soundFile:"audio/harmony.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"have",cefr:"A1",ipa:"/hæv/",ce:"hav",sounds:2,enDef:"To possess.",jpWord:"持つ",jpDef:"所有する",soundFile:"audio/have.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"head",cefr:"A1",ipa:"/hɛd/",ce:"hed",sounds:2,enDef:"Top part of body.",jpWord:"頭",jpDef:"体の上部",soundFile:"audio/head.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"he",cefr:"A1",ipa:"/hiː/",ce:"hee",sounds:1,enDef:"Male person.",jpWord:"彼",jpDef:"男性",soundFile:"audio/he.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"heir",cefr:"B2",ipa:"/ɛər/",ce:"air",sounds:1,enDef:"Someone who inherits.",jpWord:"相続人",jpDef:"遺産を受け継ぐ人",soundFile:"audio/heir.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"help",cefr:"A1",ipa:"/hɛlp/",ce:"help",sounds:4,enDef:"To assist.",jpWord:"助ける",jpDef:"手伝う",soundFile:"audio/help.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"her",cefr:"A1",ipa:"/hɜːr/",ce:"her",sounds:1,enDef:"Belonging to a woman.",jpWord:"彼女の",jpDef:"女性の所有",soundFile:"audio/her.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"height",cefr:"A2",ipa:"/haɪt/",ce:"hite",sounds:2,enDef:"How tall something is.",jpWord:"高さ",jpDef:"背丈",soundFile:"audio/height.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"high",cefr:"A1",ipa:"/haɪ/",ce:"hye",sounds:1,enDef:"Far above ground.",jpWord:"高い",jpDef:"上の方",soundFile:"audio/high.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"him",cefr:"A1",ipa:"/hɪm/",ce:"him",sounds:2,enDef:"Object form of he.",jpWord:"彼を",jpDef:"男性の目的格",soundFile:"audio/him.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"home",cefr:"A1",ipa:"/hoʊm/",ce:"hohm",sounds:1,enDef:"Place where you live.",jpWord:"家",jpDef:"住む場所",soundFile:"audio/home.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"honest",cefr:"A2",ipa:"/ˈɒnɪst/",ce:"on-ist",sounds:4,enDef:"Telling the truth.",jpWord:"正直な",jpDef:"嘘をつかない",soundFile:"audio/honest.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"hope",cefr:"A1",ipa:"/hoʊp/",ce:"hohp",sounds:2,enDef:"To want something to happen.",jpWord:"望む",jpDef:"期待する",soundFile:"audio/hope.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"hot",cefr:"A1",ipa:"/hɒt/",ce:"hot",sounds:2,enDef:"High temperature.",jpWord:"暑い",jpDef:"熱い",soundFile:"audio/hot.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"hour",cefr:"A1",ipa:"/aʊər/",ce:"our",sounds:2,enDef:"60 minutes.",jpWord:"時間",jpDef:"60分",soundFile:"audio/hour.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"house",cefr:"A1",ipa:"/haʊs/",ce:"hows",sounds:2,enDef:"A building to live in.",jpWord:"家",jpDef:"住居",soundFile:"audio/house.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"how",cefr:"A1",ipa:"/haʊ/",ce:"how",sounds:1,enDef:"Asking in what way.",jpWord:"どう",jpDef:"どのように",soundFile:"audio/how.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"im",cefr:"A1",ipa:"/ɪm/",ce:"im",sounds:1,enDef:"Short for 'I am'.",jpWord:"私は",jpDef:"I amの略",soundFile:"audio/'im.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ignite",cefr:"B2",ipa:"/ɪɡˈnaɪt/",ce:"ig-nyte",sounds:4,enDef:"To set on fire.",jpWord:"点火する",jpDef:"火をつける",soundFile:"audio/ignite.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"indict",cefr:"B2",ipa:"/ɪnˈdaɪt/",ce:"in-dyte",sounds:3,enDef:"To formally accuse.",jpWord:"起訴する",jpDef:"告発する",soundFile:"audio/indict.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"individual",cefr:"B1",ipa:"/ˌɪndɪˈvɪdʒuəl/",ce:"in-duh-vij-oo-uhl",sounds:8,enDef:"A single person.",jpWord:"個人",jpDef:"一人",soundFile:"audio/individual.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"island",cefr:"A1",ipa:"/ˈaɪlənd/",ce:"eye-lund",sounds:3,enDef:"Land surrounded by water.",jpWord:"島",jpDef:"水に囲まれた土地",soundFile:"audio/island.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"jam",cefr:"A1",ipa:"/dʒæm/",ce:"jam",sounds:2,enDef:"Fruit spread.",jpWord:"ジャム",jpDef:"果物のペースト",soundFile:"audio/jam.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"jalapeño",cefr:"B2",ipa:"/ˌhɑːləˈpeɪnjoʊ/",ce:"hah-luh-pay-nyoh",sounds:7,enDef:"A spicy pepper.",jpWord:"ハラペーニョ",jpDef:"辛い唐辛子",soundFile:"audio/jalapeno.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"jump",cefr:"A1",ipa:"/dʒʌmp/",ce:"jump",sounds:4,enDef:"To leap into the air.",jpWord:"跳ぶ",jpDef:"ジャンプする",soundFile:"audio/jump.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"jumped",cefr:"A1",ipa:"/dʒʌmpt/",ce:"jumpt",sounds:5,enDef:"Past of jump.",jpWord:"跳んだ",jpDef:"ジャンプした",soundFile:"audio/jumped.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"June",cefr:"A1",ipa:"/dʒuːn/",ce:"joon",sounds:2,enDef:"The sixth month.",jpWord:"6月",jpDef:"六月",soundFile:"audio/june.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"key",cefr:"A1",ipa:"/kiː/",ce:"kee",sounds:1,enDef:"Object that opens a lock.",jpWord:"鍵",jpDef:"かぎ",soundFile:"audio/key.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"kite",cefr:"A1",ipa:"/kaɪt/",ce:"kyte",sounds:2,enDef:"Toy that flies in the air.",jpWord:"凧",jpDef:"たこ",soundFile:"audio/kite.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"knife",cefr:"A1",ipa:"/naɪf/",ce:"nyfe",sounds:2,enDef:"A cutting tool.",jpWord:"ナイフ",jpDef:"刃物",soundFile:"audio/knife.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"knives",cefr:"A2",ipa:"/naɪvz/",ce:"nyvz",sounds:3,enDef:"Plural of knife.",jpWord:"ナイフ（複数）",jpDef:"ナイフの複数形",soundFile:"audio/knives.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"know",cefr:"A1",ipa:"/noʊ/",ce:"no",sounds:1,enDef:"To have knowledge.",jpWord:"知る",jpDef:"わかる",soundFile:"audio/know.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"language",cefr:"A1",ipa:"/ˈlæŋɡwɪdʒ/",ce:"lang-gwij",sounds:6,enDef:"A system of communication.",jpWord:"言語",jpDef:"ことば",soundFile:"audio/language.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"lamb",cefr:"A1",ipa:"/læm/",ce:"lam",sounds:2,enDef:"A young sheep.",jpWord:"子羊",jpDef:"若い羊",soundFile:"audio/lamb.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"laugh",cefr:"A1",ipa:"/læf/",ce:"laf",sounds:3,enDef:"To make a happy sound.",jpWord:"笑う",jpDef:"声を出して笑う",soundFile:"audio/laugh.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"laughed",cefr:"A1",ipa:"/læft/",ce:"laft",sounds:4,enDef:"Past of laugh.",jpWord:"笑った",jpDef:"笑うの過去",soundFile:"audio/laughed.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"lawn",cefr:"A1",ipa:"/lɔːn/",ce:"lawn",sounds:1,enDef:"Grass in a yard.",jpWord:"芝生",jpDef:"庭の草地",soundFile:"audio/lawn.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"lazy",cefr:"A1",ipa:"/ˈleɪzi/",ce:"lay-zee",sounds:3,enDef:"Not wanting to work.",jpWord:"怠けた",jpDef:"なまけている",soundFile:"audio/lazy.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"leaf",cefr:"A1",ipa:"/liːf/",ce:"leef",sounds:1,enDef:"Part of a plant.",jpWord:"葉",jpDef:"植物の一部",soundFile:"audio/leaf.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"late",cefr:"A1",ipa:"/leɪt/",ce:"layt",sounds:2,enDef:"After the expected time.",jpWord:"遅い",jpDef:"遅れた",soundFile:"audio/late.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"law",cefr:"A2",ipa:"/lɔː/",ce:"law",sounds:1,enDef:"A rule.",jpWord:"法律",jpDef:"きまり",soundFile:"audio/law.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"lemon",cefr:"A1",ipa:"/ˈlɛmən/",ce:"lem-un",sounds:3,enDef:"A yellow fruit.",jpWord:"レモン",jpDef:"黄色い果物",soundFile:"audio/lemon.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"leopard",cefr:"A2",ipa:"/ˈlɛpərd/",ce:"lep-erd",sounds:4,enDef:"A large spotted cat.",jpWord:"ヒョウ",jpDef:"大型の猫科",soundFile:"audio/leopard.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"letter",cefr:"A1",ipa:"/ˈlɛtər/",ce:"let-er",sounds:3,enDef:"A written message.",jpWord:"手紙",jpDef:"書かれたメッセージ",soundFile:"audio/letter.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"life",cefr:"A1",ipa:"/laɪf/",ce:"lyfe",sounds:2,enDef:"The state of being alive.",jpWord:"命",jpDef:"生きていること",soundFile:"audio/life.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"light",cefr:"A1",ipa:"/laɪt/",ce:"lyte",sounds:2,enDef:"Brightness.",jpWord:"光",jpDef:"明るさ",soundFile:"audio/light.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"little",cefr:"A1",ipa:"/ˈlɪtəl/",ce:"lit-ul",sounds:3,enDef:"Small.",jpWord:"小さい",jpDef:"少しの",soundFile:"audio/little.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"live",cefr:"A1",ipa:"/lɪv/",ce:"liv",sounds:2,enDef:"To be alive.",jpWord:"生きる",jpDef:"生活する",soundFile:"audio/live.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"lives",cefr:"A1",ipa:"/lɪvz/",ce:"livz",sounds:3,enDef:"Plural of life.",jpWord:"命（複数）",jpDef:"いくつもの命",soundFile:"audio/lives.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"long",cefr:"A1",ipa:"/lɔːŋ/",ce:"lawng",sounds:3,enDef:"Not short.",jpWord:"長い",jpDef:"長さがある",soundFile:"audio/long.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"longer",cefr:"A1",ipa:"/ˈlɔːŋɡər/",ce:"lawng-ger",sounds:4,enDef:"More long.",jpWord:"より長い",jpDef:"もっと長い",soundFile:"audio/longer.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"look",cefr:"A1",ipa:"/lʊk/",ce:"luk",sounds:2,enDef:"To see.",jpWord:"見る",jpDef:"視線を向ける",soundFile:"audio/look.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"love",cefr:"A1",ipa:"/lʌv/",ce:"luv",sounds:2,enDef:"Strong feeling of affection.",jpWord:"愛",jpDef:"愛情",soundFile:"audio/love.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"low",cefr:"A1",ipa:"/loʊ/",ce:"loh",sounds:1,enDef:"Not high.",jpWord:"低い",jpDef:"下の方",soundFile:"audio/low.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"luck",cefr:"A1",ipa:"/lʌk/",ce:"luk",sounds:3,enDef:"Good fortune.",jpWord:"運",jpDef:"幸運",soundFile:"audio/luck.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"luxury",cefr:"B2",ipa:"/ˈlʌkʃəri/",ce:"luk-shuh-ree",sounds:4,enDef:"Something very comfortable.",jpWord:"贅沢",jpDef:"ぜいたくなもの",soundFile:"audio/luxury.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"machine",cefr:"A2",ipa:"/məˈʃiːn/",ce:"muh-sheen",sounds:3,enDef:"A device that does work.",jpWord:"機械",jpDef:"きかい",soundFile:"audio/machine.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"make",cefr:"A1",ipa:"/meɪk/",ce:"make",sounds:2,enDef:"To create something.",jpWord:"作る",jpDef:"つくる",soundFile:"audio/make.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"man",cefr:"A1",ipa:"/mæn/",ce:"man",sounds:2,enDef:"An adult male.",jpWord:"男性",jpDef:"だんせい",soundFile:"audio/man.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"many",cefr:"A1",ipa:"/ˈmɛni/",ce:"men-ee",sounds:3,enDef:"A large number.",jpWord:"たくさん",jpDef:"多くの",soundFile:"audio/many.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"map",cefr:"A1",ipa:"/mæp/",ce:"map",sounds:2,enDef:"A picture of a place.",jpWord:"地図",jpDef:"ちず",soundFile:"audio/map.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"marry",cefr:"A2",ipa:"/ˈmæri/",ce:"mar-ee",sounds:3,enDef:"To become a spouse.",jpWord:"結婚する",jpDef:"けっこんする",soundFile:"audio/marry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"mean",cefr:"A2",ipa:"/miːn/",ce:"meen",sounds:1,enDef:"To intend.",jpWord:"意味する",jpDef:"いみする",soundFile:"audio/mean.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"measure",cefr:"B1",ipa:"/ˈmɛʒər/",ce:"mezh-er",sounds:3,enDef:"To find size or amount.",jpWord:"測る",jpDef:"はかる",soundFile:"audio/measure.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"me",cefr:"A1",ipa:"/miː/",ce:"mee",sounds:1,enDef:"Refers to oneself.",jpWord:"私を",jpDef:"わたしを",soundFile:"audio/me.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"merry",cefr:"B1",ipa:"/ˈmɛri/",ce:"mer-ee",sounds:3,enDef:"Happy and cheerful.",jpWord:"陽気な",jpDef:"ようきな",soundFile:"audio/merry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"million",cefr:"A2",ipa:"/ˈmɪljən/",ce:"mil-yun",sounds:3,enDef:"One thousand thousand.",jpWord:"百万",jpDef:"ひゃくまん",soundFile:"audio/million.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"milk",cefr:"A1",ipa:"/mɪlk/",ce:"milk",sounds:3,enDef:"A white drink.",jpWord:"牛乳",jpDef:"ぎゅうにゅう",soundFile:"audio/milk.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"mirage",cefr:"B2",ipa:"/mɪˈrɑːʒ/",ce:"mih-rahzh",sounds:3,enDef:"An optical illusion.",jpWord:"蜃気楼",jpDef:"しんきろう",soundFile:"audio/mirage.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"mirror",cefr:"A1",ipa:"/ˈmɪrər/",ce:"mir-er",sounds:3,enDef:"A reflective surface.",jpWord:"鏡",jpDef:"かがみ",soundFile:"audio/mirror.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"mnemonic",cefr:"C1",ipa:"/nəˈmɒnɪk/",ce:"nuh-mon-ik",sounds:3,enDef:"A memory aid.",jpWord:"記憶術",jpDef:"きおくじゅつ",soundFile:"audio/mnemonic.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"money",cefr:"A1",ipa:"/ˈmʌni/",ce:"mun-ee",sounds:3,enDef:"Used to buy things.",jpWord:"お金",jpDef:"おかね",soundFile:"audio/money.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"motion",cefr:"B1",ipa:"/ˈmoʊʃən/",ce:"moh-shun",sounds:3,enDef:"Movement.",jpWord:"動き",jpDef:"うごき",soundFile:"audio/motion.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"mother",cefr:"A1",ipa:"/ˈmʌðər/",ce:"muh-ther",sounds:3,enDef:"A female parent.",jpWord:"母",jpDef:"はは",soundFile:"audio/mother.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"move",cefr:"A1",ipa:"/muːv/",ce:"moov",sounds:1,enDef:"To change position.",jpWord:"動く",jpDef:"うごく",soundFile:"audio/move.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"music",cefr:"A1",ipa:"/ˈmjuːzɪk/",ce:"myoo-zik",sounds:3,enDef:"Sound arranged in rhythm.",jpWord:"音楽",jpDef:"おんがく",soundFile:"audio/music.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"my",cefr:"A1",ipa:"/maɪ/",ce:"my",sounds:1,enDef:"Belonging to me.",jpWord:"私の",jpDef:"わたしの",soundFile:"audio/my.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"myth",cefr:"B2",ipa:"/mɪθ/",ce:"mith",sounds:2,enDef:"A traditional story.",jpWord:"神話",jpDef:"しんわ",soundFile:"audio/myth.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"nature",cefr:"A2",ipa:"/ˈneɪtʃər/",ce:"nay-chur",sounds:3,enDef:"The natural world.",jpWord:"自然",jpDef:"しぜん",soundFile:"audio/nature.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"neither",cefr:"B1",ipa:"/ˈnaɪðər/",ce:"ny-ther",sounds:3,enDef:"Not one or the other.",jpWord:"どちらも…ない",jpDef:"どちらもない",soundFile:"audio/neither.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"net",cefr:"A1",ipa:"/nɛt/",ce:"net",sounds:2,enDef:"A mesh for catching.",jpWord:"網",jpDef:"あみ",soundFile:"audio/net.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"neutral",cefr:"B2",ipa:"/ˈnjuːtrəl/",ce:"new-trul",sounds:3,enDef:"Not taking sides.",jpWord:"中立の",jpDef:"ちゅうりつの",soundFile:"audio/neutral.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"never",cefr:"A1",ipa:"/ˈnɛvər/",ce:"nev-er",sounds:3,enDef:"At no time.",jpWord:"決して…ない",jpDef:"けっしてない",soundFile:"audio/never.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"new",cefr:"A1",ipa:"/njuː/",ce:"new",sounds:1,enDef:"Not old.",jpWord:"新しい",jpDef:"あたらしい",soundFile:"audio/new.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"next",cefr:"A1",ipa:"/nɛkst/",ce:"next",sounds:4,enDef:"After this.",jpWord:"次の",jpDef:"つぎの",soundFile:"audio/next.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"night",cefr:"A1",ipa:"/naɪt/",ce:"nite",sounds:2,enDef:"Dark time of day.",jpWord:"夜",jpDef:"よる",soundFile:"audio/night.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"north",cefr:"A1",ipa:"/nɔːrθ/",ce:"north",sounds:3,enDef:"Opposite of south.",jpWord:"北",jpDef:"きた",soundFile:"audio/north.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"now",cefr:"A1",ipa:"/naʊ/",ce:"now",sounds:1,enDef:"At this time.",jpWord:"今",jpDef:"いま",soundFile:"audio/now.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"nurse",cefr:"A1",ipa:"/nɜːrs/",ce:"nurse",sounds:3,enDef:"A medical helper.",jpWord:"看護師",jpDef:"かんごし",soundFile:"audio/nurse.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"official",cefr:"B1",ipa:"/əˈfɪʃəl/",ce:"uh-fish-ul",sounds:3,enDef:"Approved by authority.",jpWord:"公式の",jpDef:"こうしきの",soundFile:"audio/official.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"of",cefr:"A1",ipa:"/ʌv/",ce:"uhv",sounds:1,enDef:"Belonging to.",jpWord:"〜の",jpDef:"の",soundFile:"audio/of.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"oil",cefr:"A1",ipa:"/ɔɪl/",ce:"oil",sounds:2,enDef:"A slippery liquid.",jpWord:"油",jpDef:"あぶら",soundFile:"audio/oil.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"one",cefr:"A1",ipa:"/wʌn/",ce:"wun",sounds:1,enDef:"Number 1.",jpWord:"一",jpDef:"いち",soundFile:"audio/one.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"onion",cefr:"A1",ipa:"/ˈʌnjən/",ce:"un-yun",sounds:3,enDef:"A round vegetable.",jpWord:"玉ねぎ",jpDef:"たまねぎ",soundFile:"audio/onion.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"open",cefr:"A1",ipa:"/ˈoʊpən/",ce:"oh-pen",sounds:2,enDef:"Not closed.",jpWord:"開く",jpDef:"ひらく",soundFile:"audio/open.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"opt",cefr:"B2",ipa:"/ɒpt/",ce:"opt",sounds:3,enDef:"To choose.",jpWord:"選ぶ",jpDef:"えらぶ",soundFile:"audio/opt.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"out",cefr:"A1",ipa:"/aʊt/",ce:"out",sounds:1,enDef:"Not inside.",jpWord:"外",jpDef:"そと",soundFile:"audio/out.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"paint",cefr:"A1",ipa:"/peɪnt/",ce:"paynt",sounds:3,enDef:"Colored liquid.",jpWord:"絵の具",jpDef:"えのぐ",soundFile:"audio/paint.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"palm",cefr:"A2",ipa:"/pɑːm/",ce:"pahm",sounds:2,enDef:"Inside of the hand.",jpWord:"手のひら",jpDef:"てのひら",soundFile:"audio/palm.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"parliament",cefr:"B2",ipa:"/ˈpɑːrləmənt/",ce:"par-luh-ment",sounds:4,enDef:"A law-making body.",jpWord:"議会",jpDef:"ぎかい",soundFile:"audio/parliament.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pause",cefr:"A2",ipa:"/pɔːz/",ce:"paws",sounds:1,enDef:"To stop briefly.",jpWord:"一時停止",jpDef:"いちじていし",soundFile:"audio/pause.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"penguin",cefr:"A2",ipa:"/ˈpɛŋɡwɪn/",ce:"pen-gwin",sounds:3,enDef:"A flightless bird.",jpWord:"ペンギン",jpDef:"ペンギン",soundFile:"audio/penguin.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pen",cefr:"A1",ipa:"/pɛn/",ce:"pen",sounds:2,enDef:"A writing tool.",jpWord:"ペン",jpDef:"ペン",soundFile:"audio/pen.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pencil",cefr:"A1",ipa:"/ˈpɛnsəl/",ce:"pen-sul",sounds:3,enDef:"A writing tool.",jpWord:"鉛筆",jpDef:"えんぴつ",soundFile:"audio/pencil.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"people",cefr:"A1",ipa:"/ˈpiːpəl/",ce:"pee-pul",sounds:3,enDef:"Human beings.",jpWord:"人々",jpDef:"ひとびと",soundFile:"audio/people.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"perhaps",cefr:"B1",ipa:"/pəˈhæps/",ce:"per-haps",sounds:3,enDef:"Maybe.",jpWord:"おそらく",jpDef:"おそらく",soundFile:"audio/perhaps.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"phlegm",cefr:"C1",ipa:"/flɛm/",ce:"flem",sounds:2,enDef:"Thick mucus.",jpWord:"痰",jpDef:"たん",soundFile:"audio/phlegm.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"phone",cefr:"A1",ipa:"/foʊn/",ce:"fone",sounds:1,enDef:"A mobile device.",jpWord:"電話",jpDef:"でんわ",soundFile:"audio/phone.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"photo",cefr:"A1",ipa:"/ˈfoʊtoʊ/",ce:"foh-toh",sounds:2,enDef:"A picture.",jpWord:"写真",jpDef:"しゃしん",soundFile:"audio/photo.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"picture",cefr:"A1",ipa:"/ˈpɪktʃər/",ce:"pik-chur",sounds:3,enDef:"An image.",jpWord:"絵",jpDef:"え",soundFile:"audio/picture.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pie",cefr:"A1",ipa:"/paɪ/",ce:"pie",sounds:1,enDef:"A baked dessert.",jpWord:"パイ",jpDef:"パイ",soundFile:"audio/pie.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pizza",cefr:"A1",ipa:"/ˈpiːtsə/",ce:"peet-suh",sounds:2,enDef:"A flat baked food.",jpWord:"ピザ",jpDef:"ピザ",soundFile:"audio/pizza.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"play",cefr:"A1",ipa:"/pleɪ/",ce:"play",sounds:2,enDef:"To have fun.",jpWord:"遊ぶ",jpDef:"あそぶ",soundFile:"audio/play.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"played",cefr:"A1",ipa:"/pleɪd/",ce:"playd",sounds:3,enDef:"Past of play.",jpWord:"遊んだ",jpDef:"あそんだ",soundFile:"audio/played.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"police",cefr:"A1",ipa:"/pəˈliːs/",ce:"puh-lees",sounds:3,enDef:"Law officers.",jpWord:"警察",jpDef:"けいさつ",soundFile:"audio/police.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"possible",cefr:"A2",ipa:"/ˈpɒsəbəl/",ce:"pos-uh-bul",sounds:3,enDef:"Able to happen.",jpWord:"可能な",jpDef:"かのうな",soundFile:"audio/possible.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"prey",cefr:"B2",ipa:"/preɪ/",ce:"pray",sounds:1,enDef:"An animal hunted.",jpWord:"獲物",jpDef:"えもの",soundFile:"audio/prey.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pretty",cefr:"A1",ipa:"/ˈprɪti/",ce:"prit-ee",sounds:3,enDef:"Nice to look at.",jpWord:"かわいい",jpDef:"かわいい",soundFile:"audio/pretty.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"prove",cefr:"B1",ipa:"/pruːv/",ce:"proov",sounds:1,enDef:"To show as true.",jpWord:"証明する",jpDef:"しょうめいする",soundFile:"audio/prove.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"psalm",cefr:"C1",ipa:"/sɑːm/",ce:"sahm",sounds:2,enDef:"A sacred song.",jpWord:"詩編",jpDef:"しへん",soundFile:"audio/psalm.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"psychology",cefr:"B2",ipa:"/saɪˈkɒlədʒi/",ce:"sy-kol-uh-jee",sounds:4,enDef:"Study of the mind.",jpWord:"心理学",jpDef:"しんりがく",soundFile:"audio/psychology.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pterodactyl",cefr:"C1",ipa:"/ˌtɛrəˈdæktɪl/",ce:"ter-uh-dak-til",sounds:4,enDef:"A flying dinosaur.",jpWord:"プテラノドン",jpDef:"プテラノドン",soundFile:"audio/pterodactyl.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"purple",cefr:"A1",ipa:"/ˈpɜːrpəl/",ce:"pur-pul",sounds:3,enDef:"A color.",jpWord:"紫",jpDef:"むらさき",soundFile:"audio/purple.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"push",cefr:"A1",ipa:"/pʊʃ/",ce:"push",sounds:2,enDef:"To move forward.",jpWord:"押す",jpDef:"おす",soundFile:"audio/push.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"put",cefr:"A1",ipa:"/pʊt/",ce:"put",sounds:2,enDef:"To place.",jpWord:"置く",jpDef:"おく",soundFile:"audio/put.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"quartz",cefr:"B2",ipa:"/kwɔːrts/",ce:"kworts",sounds:4,enDef:"A type of mineral.",jpWord:"水晶",jpDef:"すいしょう",soundFile:"audio/quartz.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"queen",cefr:"A1",ipa:"/kwiːn/",ce:"kween",sounds:2,enDef:"A female ruler.",jpWord:"女王",jpDef:"じょおう",soundFile:"audio/queen.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"quick",cefr:"A1",ipa:"/kwɪk/",ce:"kwik",sounds:3,enDef:"Fast.",jpWord:"速い",jpDef:"はやい",soundFile:"audio/quick.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"quiet",cefr:"A1",ipa:"/ˈkwaɪət/",ce:"kwy-et",sounds:3,enDef:"Not loud.",jpWord:"静かな",jpDef:"しずかな",soundFile:"audio/quiet.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"quit",cefr:"A1",ipa:"/kwɪt/",ce:"kwit",sounds:3,enDef:"To stop.",jpWord:"やめる",jpDef:"やめる",soundFile:"audio/quit.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rabbit",cefr:"A1",ipa:"/ˈræbɪt/",ce:"rab-it",sounds:3,enDef:"A small hopping animal.",jpWord:"ウサギ",jpDef:"ウサギ",soundFile:"audio/rabbit.mp3",tallies:{hard:0,skip:0,easy:0}},,
{word:"rain",cefr:"A1",ipa:"/reɪn/",ce:"rain",sounds:2,enDef:"Water from the sky.",jpWord:"雨",jpDef:"あめ",soundFile:"audio/rain.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"raspberry",cefr:"A2",ipa:"/ˈræzˌbɛri/",ce:"raz-ber-ee",sounds:4,enDef:"A small red fruit.",jpWord:"ラズベリー",jpDef:"ラズベリー",soundFile:"audio/raspberry.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"realm",cefr:"B2",ipa:"/rɛlm/",ce:"relm",sounds:3,enDef:"A kingdom or field.",jpWord:"領域",jpDef:"りょういき",soundFile:"audio/realm.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"receive",cefr:"A2",ipa:"/rɪˈsiːv/",ce:"ri-seev",sounds:3,enDef:"To get something.",jpWord:"受け取る",jpDef:"うけとる",soundFile:"audio/receive.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"receipt",cefr:"B1",ipa:"/rɪˈsiːt/",ce:"ri-seet",sounds:3,enDef:"Proof of payment.",jpWord:"領収書",jpDef:"りょうしゅうしょ",soundFile:"audio/receipt.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"red",cefr:"A1",ipa:"/rɛd/",ce:"red",sounds:2,enDef:"A color.",jpWord:"赤",jpDef:"あか",soundFile:"audio/red.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"reign",cefr:"B2",ipa:"/reɪn/",ce:"rain",sounds:2,enDef:"To rule as king.",jpWord:"統治",jpDef:"とうち",soundFile:"audio/reign.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"relation",cefr:"B1",ipa:"/rɪˈleɪʃən/",ce:"ri-lay-shun",sounds:4,enDef:"A connection.",jpWord:"関係",jpDef:"かんけい",soundFile:"audio/relation.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rendezvous",cefr:"C1",ipa:"/ˈrɒndɪvuː/",ce:"ron-deh-voo",sounds:3,enDef:"A planned meeting.",jpWord:"待ち合わせ",jpDef:"まちあわせ",soundFile:"audio/rendezvous.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ribbon",cefr:"A2",ipa:"/ˈrɪbən/",ce:"rib-un",sounds:3,enDef:"A thin strip of cloth.",jpWord:"リボン",jpDef:"リボン",soundFile:"audio/ribbon.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ride",cefr:"A1",ipa:"/raɪd/",ce:"ride",sounds:2,enDef:"To travel on.",jpWord:"乗る",jpDef:"のる",soundFile:"audio/ride.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rider",cefr:"A2",ipa:"/ˈraɪdər/",ce:"ry-der",sounds:3,enDef:"One who rides.",jpWord:"乗り手",jpDef:"のりて",soundFile:"audio/rider.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"ring",cefr:"A1",ipa:"/rɪŋ/",ce:"ring",sounds:3,enDef:"A circular band.",jpWord:"指輪",jpDef:"ゆびわ",soundFile:"audio/ring.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rhinoceros",cefr:"B2",ipa:"/raɪˈnɒsərəs/",ce:"ry-noss-er-us",sounds:5,enDef:"A large animal.",jpWord:"サイ",jpDef:"サイ",soundFile:"audio/rhinoceros.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rhyme",cefr:"A2",ipa:"/raɪm/",ce:"rime",sounds:2,enDef:"Words that sound alike.",jpWord:"韻",jpDef:"いん",soundFile:"audio/rhyme.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rhythm",cefr:"B1",ipa:"/ˈrɪðəm/",ce:"ri-thum",sounds:3,enDef:"Beat of music.",jpWord:"リズム",jpDef:"リズム",soundFile:"audio/rhythm.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rocket",cefr:"A2",ipa:"/ˈrɒkɪt/",ce:"rok-it",sounds:3,enDef:"A space vehicle.",jpWord:"ロケット",jpDef:"ロケット",soundFile:"audio/rocket.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"room",cefr:"A1",ipa:"/ruːm/",ce:"room",sounds:1,enDef:"A space in a building.",jpWord:"部屋",jpDef:"へや",soundFile:"audio/room.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rose",cefr:"A1",ipa:"/roʊz/",ce:"rose",sounds:2,enDef:"A flower.",jpWord:"バラ",jpDef:"バラ",soundFile:"audio/rose.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"rule",cefr:"A2",ipa:"/ruːl/",ce:"rool",sounds:1,enDef:"A law or guide.",jpWord:"規則",jpDef:"きそく",soundFile:"audio/rule.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"runner",cefr:"A2",ipa:"/ˈrʌnər/",ce:"run-er",sounds:3,enDef:"One who runs.",jpWord:"走者",jpDef:"そうしゃ",soundFile:"audio/runner.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"salmon",cefr:"A2",ipa:"/ˈsæmən/",ce:"sam-un",sounds:3,enDef:"A type of fish.",jpWord:"サケ",jpDef:"サケ",soundFile:"audio/salmon.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sand",cefr:"A1",ipa:"/sænd/",ce:"sand",sounds:3,enDef:"Tiny grains.",jpWord:"砂",jpDef:"すな",soundFile:"audio/sand.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"saw",cefr:"A1",ipa:"/sɔː/",ce:"saw",sounds:1,enDef:"Past of see.",jpWord:"見た",jpDef:"みた",soundFile:"audio/saw.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"scene",cefr:"A2",ipa:"/siːn/",ce:"seen",sounds:1,enDef:"A place or part.",jpWord:"場面",jpDef:"ばめん",soundFile:"audio/scene.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"school",cefr:"A1",ipa:"/skuːl/",ce:"skool",sounds:2,enDef:"A place to learn.",jpWord:"学校",jpDef:"がっこう",soundFile:"audio/school.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"science",cefr:"A2",ipa:"/ˈsaɪəns/",ce:"sigh-ence",sounds:3,enDef:"Study of nature.",jpWord:"科学",jpDef:"かがく",soundFile:"audio/science.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"scissors",cefr:"A1",ipa:"/ˈsɪzərz/",ce:"siz-erz",sounds:3,enDef:"A cutting tool.",jpWord:"はさみ",jpDef:"はさみ",soundFile:"audio/scissors.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"scope",cefr:"B1",ipa:"/skoʊp/",ce:"scope",sounds:1,enDef:"Range or extent.",jpWord:"範囲",jpDef:"はんい",soundFile:"audio/scope.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"self",cefr:"A2",ipa:"/sɛlf/",ce:"self",sounds:3,enDef:"Your identity.",jpWord:"自分",jpDef:"じぶん",soundFile:"audio/self.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"serve",cefr:"A1",ipa:"/sɜːrv/",ce:"serv",sounds:2,enDef:"To help or give.",jpWord:"提供する",jpDef:"ていきょうする",soundFile:"audio/serve.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"shame",cefr:"B1",ipa:"/ʃeɪm/",ce:"shame",sounds:2,enDef:"A bad feeling.",jpWord:"恥",jpDef:"はじ",soundFile:"audio/shame.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"shirt",cefr:"A1",ipa:"/ʃɜːrt/",ce:"shirt",sounds:3,enDef:"Clothing for upper body.",jpWord:"シャツ",jpDef:"シャツ",soundFile:"audio/shirt.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"shout",cefr:"A1",ipa:"/ʃaʊt/",ce:"shout",sounds:2,enDef:"To yell.",jpWord:"叫ぶ",jpDef:"さけぶ",soundFile:"audio/shout.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"shy",cefr:"A1",ipa:"/ʃaɪ/",ce:"shy",sounds:1,enDef:"Quiet or timid.",jpWord:"内気な",jpDef:"うちきな",soundFile:"audio/shy.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"signal",cefr:"A2",ipa:"/ˈsɪɡnəl/",ce:"sig-nul",sounds:3,enDef:"A sign or message.",jpWord:"信号",jpDef:"しんごう",soundFile:"audio/signal.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sign",cefr:"A1",ipa:"/saɪn/",ce:"sine",sounds:1,enDef:"A mark or symbol.",jpWord:"サイン",jpDef:"サイン",soundFile:"audio/sign.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sing",cefr:"A1",ipa:"/sɪŋ/",ce:"sing",sounds:3,enDef:"To make music.",jpWord:"歌う",jpDef:"うたう",soundFile:"audio/sing.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sit",cefr:"A1",ipa:"/sɪt/",ce:"sit",sounds:2,enDef:"To rest on a chair.",jpWord:"座る",jpDef:"すわる",soundFile:"audio/sit.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"six",cefr:"A1",ipa:"/sɪks/",ce:"siks",sounds:3,enDef:"Number 6.",jpWord:"六",jpDef:"ろく",soundFile:"audio/six.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"skin",cefr:"A1",ipa:"/skɪn/",ce:"skin",sounds:3,enDef:"Body covering.",jpWord:"皮膚",jpDef:"ひふ",soundFile:"audio/skin.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"snow",cefr:"A1",ipa:"/snoʊ/",ce:"snow",sounds:2,enDef:"Frozen rain.",jpWord:"雪",jpDef:"ゆき",soundFile:"audio/snow.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sofa",cefr:"A1",ipa:"/ˈsoʊfə/",ce:"soh-fuh",sounds:2,enDef:"A seat.",jpWord:"ソファ",jpDef:"ソファ",soundFile:"audio/sofa.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"solemn",cefr:"B2",ipa:"/ˈsɒləm/",ce:"sol-um",sounds:3,enDef:"Serious.",jpWord:"厳粛な",jpDef:"げんしゅくな",soundFile:"audio/solemn.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"some",cefr:"A1",ipa:"/sʌm/",ce:"sum",sounds:1,enDef:"An amount.",jpWord:"いくつか",jpDef:"いくつか",soundFile:"audio/some.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"son",cefr:"A1",ipa:"/sʌn/",ce:"sun",sounds:1,enDef:"A male child.",jpWord:"息子",jpDef:"むすこ",soundFile:"audio/son.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"speak",cefr:"A1",ipa:"/spiːk/",ce:"speek",sounds:2,enDef:"To talk.",jpWord:"話す",jpDef:"はなす",soundFile:"audio/speak.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"special",cefr:"A1",ipa:"/ˈspɛʃəl/",ce:"spesh-ul",sounds:3,enDef:"Not ordinary.",jpWord:"特別な",jpDef:"とくべつな",soundFile:"audio/special.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"spread",cefr:"A2",ipa:"/sprɛd/",ce:"spred",sounds:4,enDef:"To open or move.",jpWord:"広がる",jpDef:"ひろがる",soundFile:"audio/spread.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"start",cefr:"A1",ipa:"/stɑːrt/",ce:"start",sounds:4,enDef:"To begin.",jpWord:"始める",jpDef:"はじめる",soundFile:"audio/start.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"stay",cefr:"A1",ipa:"/steɪ/",ce:"stay",sounds:2,enDef:"To remain.",jpWord:"滞在する",jpDef:"たいざいする",soundFile:"audio/stay.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"stop",cefr:"A1",ipa:"/stɒp/",ce:"stop",sounds:3,enDef:"To end movement.",jpWord:"止まる",jpDef:"とまる",soundFile:"audio/stop.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"story",cefr:"A1",ipa:"/ˈstɔːri/",ce:"stor-ee",sounds:3,enDef:"A tale.",jpWord:"物語",jpDef:"ものがたり",soundFile:"audio/story.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"subtle",cefr:"B2",ipa:"/ˈsʌtəl/",ce:"sut-ul",sounds:3,enDef:"Not obvious.",jpWord:"微妙な",jpDef:"びみょうな",soundFile:"audio/subtle.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"succeed",cefr:"A2",ipa:"/səkˈsiːd/",ce:"suk-seed",sounds:3,enDef:"To do well.",jpWord:"成功する",jpDef:"せいこうする",soundFile:"audio/succeed.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sudden",cefr:"A2",ipa:"/ˈsʌdən/",ce:"sud-un",sounds:3,enDef:"Happening quickly.",jpWord:"突然の",jpDef:"とつぜんの",soundFile:"audio/sudden.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sugar",cefr:"A1",ipa:"/ˈʃʊɡər/",ce:"shug-er",sounds:3,enDef:"Sweet food.",jpWord:"砂糖",jpDef:"さとう",soundFile:"audio/sugar.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"summer",cefr:"A1",ipa:"/ˈsʌmər/",ce:"sum-er",sounds:3,enDef:"Hot season.",jpWord:"夏",jpDef:"なつ",soundFile:"audio/summer.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sun",cefr:"A1",ipa:"/sʌn/",ce:"sun",sounds:1,enDef:"Star in sky.",jpWord:"太陽",jpDef:"たいよう",soundFile:"audio/sun.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"supper",cefr:"A2",ipa:"/ˈsʌpər/",ce:"sup-er",sounds:3,enDef:"Evening meal.",jpWord:"夕食",jpDef:"ゆうしょく",soundFile:"audio/supper.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"supply",cefr:"B1",ipa:"/səˈplaɪ/",ce:"suh-ply",sounds:3,enDef:"To provide.",jpWord:"供給する",jpDef:"きょうきゅうする",soundFile:"audio/supply.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"support",cefr:"A2",ipa:"/səˈpɔːrt/",ce:"suh-port",sounds:3,enDef:"To help.",jpWord:"支える",jpDef:"ささえる",soundFile:"audio/support.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"surprise",cefr:"A1",ipa:"/sərˈpraɪz/",ce:"ser-prize",sounds:3,enDef:"Unexpected event.",jpWord:"驚き",jpDef:"おどろき",soundFile:"audio/surprise.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"sword",cefr:"A2",ipa:"/sɔːrd/",ce:"sord",sounds:2,enDef:"A long weapon.",jpWord:"剣",jpDef:"けん",soundFile:"audio/sword.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"system",cefr:"A2",ipa:"/ˈsɪstəm/",ce:"sis-tum",sounds:3,enDef:"A set of parts.",jpWord:"システム",jpDef:"システム",soundFile:"audio/system.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"table",cefr:"A1",ipa:"/ˈteɪbəl/",ce:"tay-bul",sounds:3,enDef:"A piece of furniture.",jpWord:"テーブル",jpDef:"テーブル",soundFile:"audio/table.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"take",cefr:"A1",ipa:"/teɪk/",ce:"take",sounds:2,enDef:"To get.",jpWord:"取る",jpDef:"とる",soundFile:"audio/take.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"talk",cefr:"A1",ipa:"/tɔːk/",ce:"tawk",sounds:2,enDef:"To speak.",jpWord:"話す",jpDef:"はなす",soundFile:"audio/talk.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"teacher",cefr:"A1",ipa:"/ˈtiːtʃər/",ce:"tee-chur",sounds:3,enDef:"One who teaches.",jpWord:"先生",jpDef:"せんせい",soundFile:"audio/teacher.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"term",cefr:"B1",ipa:"/tɜːrm/",ce:"term",sounds:2,enDef:"A word or period.",jpWord:"用語",jpDef:"ようご",soundFile:"audio/term.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"theology",cefr:"C1",ipa:"/θiˈɒlədʒi/",ce:"thee-ol-uh-jee",sounds:4,enDef:"Study of religion.",jpWord:"神学",jpDef:"しんがく",soundFile:"audio/theology.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"them",cefr:"A1",ipa:"/ðɛm/",ce:"them",sounds:2,enDef:"Refers to people.",jpWord:"彼らを",jpDef:"かれらを",soundFile:"audio/them.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"they",cefr:"A1",ipa:"/ðeɪ/",ce:"thay",sounds:1,enDef:"Refers to people.",jpWord:"彼らは",jpDef:"かれらは",soundFile:"audio/they.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"thick",cefr:"A1",ipa:"/θɪk/",ce:"thik",sounds:3,enDef:"Not thin.",jpWord:"厚い",jpDef:"あつい",soundFile:"audio/thick.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"thin",cefr:"A1",ipa:"/θɪn/",ce:"thin",sounds:3,enDef:"Not thick.",jpWord:"薄い",jpDef:"うすい",soundFile:"audio/thin.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"this",cefr:"A1",ipa:"/ðɪs/",ce:"this",sounds:3,enDef:"Refers to something.",jpWord:"これ",jpDef:"これ",soundFile:"audio/this.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"think",cefr:"A2",ipa:"/θɪŋk/",ce:"think",sounds:3,enDef:"To use your mind to consider something.",jpWord:"考える",jpDef:"頭で物事を考える",soundFile:"audio/think.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"thumb",cefr:"A2",ipa:"/θʌm/",ce:"thum",sounds:2,enDef:"The short, thick first finger of the hand.",jpWord:"親指",jpDef:"手の一番太い指",soundFile:"audio/thumb.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"though",cefr:"B1",ipa:"/ðoʊ/",ce:"tho",sounds:1,enDef:"Used to introduce a contrasting idea.",jpWord:"〜だけれども",jpDef:"対比を示す接続詞",soundFile:"audio/though.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"through",cefr:"A2",ipa:"/θruː/",ce:"thru",sounds:2,enDef:"From one side to the other.",jpWord:"通して",jpDef:"一方から反対側へ",soundFile:"audio/through.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"tie",cefr:"A1",ipa:"/taɪ/",ce:"tai",sounds:2,enDef:"To fasten with a knot.",jpWord:"結ぶ",jpDef:"ひもなどを結ぶ",soundFile:"audio/tie.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"toe",cefr:"A1",ipa:"/toʊ/",ce:"to",sounds:1,enDef:"One of the five digits of the foot.",jpWord:"つま先",jpDef:"足の指",soundFile:"audio/toe.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"top",cefr:"A1",ipa:"/tɑp/",ce:"top",sounds:3,enDef:"The highest part of something.",jpWord:"頂上",jpDef:"一番上の部分",soundFile:"audio/top.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"tough",cefr:"B1",ipa:"/tʌf/",ce:"tuf",sounds:3,enDef:"Difficult or hard to do.",jpWord:"難しい",jpDef:"困難な",soundFile:"audio/tough.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"train",cefr:"A1",ipa:"/treɪn/",ce:"trein",sounds:4,enDef:"A vehicle that runs on tracks.",jpWord:"電車",jpDef:"線路を走る乗り物",soundFile:"audio/train.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"try",cefr:"A1",ipa:"/traɪ/",ce:"trai",sounds:2,enDef:"To attempt to do something.",jpWord:"試す",jpDef:"何かをやってみる",soundFile:"audio/try.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"truth",cefr:"B1",ipa:"/truːθ/",ce:"truth",sounds:4,enDef:"What is real or correct.",jpWord:"真実",jpDef:"本当のこと",soundFile:"audio/truth.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"turn",cefr:"A1",ipa:"/tɜːrn/",ce:"turn",sounds:3,enDef:"To move in a different direction.",jpWord:"曲がる",jpDef:"方向を変える",soundFile:"audio/turn.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"two",cefr:"A1",ipa:"/tuː/",ce:"too",sounds:1,enDef:"The number 2.",jpWord:"二",jpDef:"数字の2",soundFile:"audio/two.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"type",cefr:"A1",ipa:"/taɪp/",ce:"taip",sounds:3,enDef:"A kind or category of something.",jpWord:"種類",jpDef:"タイプや種類",soundFile:"audio/type.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"uncle",cefr:"A1",ipa:"/ˈʌŋ.kəl/",ce:"ung-kul",sounds:4,enDef:"The brother of your parent.",jpWord:"おじ",jpDef:"両親の兄弟",soundFile:"audio/uncle.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"unique",cefr:"B1",ipa:"/juːˈniːk/",ce:"yu-neek",sounds:5,enDef:"Being the only one of its kind.",jpWord:"独特な",jpDef:"他にない",soundFile:"audio/unique.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"union",cefr:"B1",ipa:"/ˈjuː.njən/",ce:"yu-nyun",sounds:5,enDef:"A group joined together.",jpWord:"連合",jpDef:"団体や組織の結合",soundFile:"audio/union.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"unicorn",cefr:"B2",ipa:"/ˈjuː.nɪ.kɔːrn/",ce:"yu-ni-korn",sounds:7,enDef:"A mythical horse with one horn.",jpWord:"ユニコーン",jpDef:"一本の角を持つ伝説の馬",soundFile:"audio/unicorn.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"use",cefr:"A1",ipa:"/juːz/",ce:"yooz",sounds:2,enDef:"To put something into action.",jpWord:"使う",jpDef:"何かを使う",soundFile:"audio/use.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"valley",cefr:"A2",ipa:"/ˈvæl.i/",ce:"val-ee",sounds:4,enDef:"A low area of land between hills.",jpWord:"谷",jpDef:"山と山の間の低地",soundFile:"audio/valley.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"van",cefr:"A1",ipa:"/væn/",ce:"van",sounds:3,enDef:"A large road vehicle for carrying goods or people.",jpWord:"バン",jpDef:"物や人を運ぶ大きな車",soundFile:"audio/van.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"vein",cefr:"B1",ipa:"/veɪn/",ce:"vayn",sounds:2,enDef:"A tube that carries blood to the heart.",jpWord:"静脈",jpDef:"血液を心臓へ運ぶ管",soundFile:"audio/vein.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"vehicle",cefr:"A2",ipa:"/ˈviː.ɪ.kəl/",ce:"vee-ih-kul",sounds:5,enDef:"A machine used for transportation.",jpWord:"車両",jpDef:"移動のための乗り物",soundFile:"audio/vehicle.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"very",cefr:"A1",ipa:"/ˈver.i/",ce:"ver-ee",sounds:3,enDef:"Used to add emphasis.",jpWord:"とても",jpDef:"程度を強める言葉",soundFile:"audio/very.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"village",cefr:"A2",ipa:"/ˈvɪl.ɪdʒ/",ce:"vil-ij",sounds:4,enDef:"A small town in the countryside.",jpWord:"村",jpDef:"小さな町や集落",soundFile:"audio/village.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"vision",cefr:"B1",ipa:"/ˈvɪʒ.ən/",ce:"vizh-un",sounds:4,enDef:"The ability to see.",jpWord:"視覚",jpDef:"見る能力",soundFile:"audio/vision.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"walk",cefr:"A1",ipa:"/wɔːk/",ce:"wawk",sounds:3,enDef:"To move on your feet.",jpWord:"歩く",jpDef:"足で移動する",soundFile:"audio/walk.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"walked",cefr:"A1",ipa:"/wɔːkt/",ce:"wawkt",sounds:4,enDef:"Past tense of walk.",jpWord:"歩いた",jpDef:"歩くの過去形",soundFile:"audio/walked.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"waltz",cefr:"B2",ipa:"/wɔːlts/",ce:"wawlts",sounds:5,enDef:"A slow ballroom dance in 3/4 time.",jpWord:"ワルツ",jpDef:"3拍子の舞踏",soundFile:"audio/waltz.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"wanted",cefr:"A1",ipa:"/ˈwɒn.tɪd/",ce:"won-tid",sounds:5,enDef:"Past tense of want.",jpWord:"欲しかった",jpDef:"欲しいの過去形",soundFile:"audio/wanted.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"water",cefr:"A1",ipa:"/ˈwɔː.tər/",ce:"waw-ter",sounds:4,enDef:"A clear liquid people drink.",jpWord:"水",jpDef:"飲み水",soundFile:"audio/water.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"we",cefr:"A1",ipa:"/wiː/",ce:"wee",sounds:1,enDef:"Refers to the speaker and others.",jpWord:"私たち",jpDef:"話し手と他の人",soundFile:"audio/we.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"Wednesday",cefr:"A1",ipa:"/ˈwenz.deɪ/",ce:"wenz-day",sounds:6,enDef:"The third day of the week.",jpWord:"水曜日",jpDef:"週の3日目",soundFile:"audio/wednesday.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"when",cefr:"A1",ipa:"/wen/",ce:"wen",sounds:3,enDef:"At what time.",jpWord:"いつ",jpDef:"時を尋ねる言葉",soundFile:"audio/when.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"where",cefr:"A1",ipa:"/wer/",ce:"wair",sounds:3,enDef:"In what place.",jpWord:"どこ",jpDef:"場所を尋ねる言葉",soundFile:"audio/where.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"which",cefr:"A1",ipa:"/wɪtʃ/",ce:"wich",sounds:4,enDef:"Asking to choose between things.",jpWord:"どちら",jpDef:"選択を尋ねる言葉",soundFile:"audio/which.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"who",cefr:"A1",ipa:"/huː/",ce:"hoo",sounds:1,enDef:"Asking about a person.",jpWord:"だれ",jpDef:"人を尋ねる言葉",soundFile:"audio/who.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"whole",cefr:"A2",ipa:"/hoʊl/",ce:"hole",sounds:2,enDef:"Complete; all of it.",jpWord:"全体",jpDef:"すべて",soundFile:"audio/whole.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"why",cefr:"A1",ipa:"/waɪ/",ce:"wai",sounds:1,enDef:"Asking for a reason.",jpWord:"なぜ",jpDef:"理由を尋ねる言葉",soundFile:"audio/why.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"will",cefr:"A1",ipa:"/wɪl/",ce:"wil",sounds:3,enDef:"Used to talk about the future.",jpWord:"〜するつもり",jpDef:"未来を表す助動詞",soundFile:"audio/will.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"win",cefr:"A1",ipa:"/wɪn/",ce:"win",sounds:3,enDef:"To be successful in a competition.",jpWord:"勝つ",jpDef:"試合に勝つ",soundFile:"audio/win.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"wolf",cefr:"A2",ipa:"/wʊlf/",ce:"wulf",sounds:4,enDef:"A wild animal related to dogs.",jpWord:"オオカミ",jpDef:"犬に似た野生動物",soundFile:"audio/wolf.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"wolves",cefr:"B1",ipa:"/wʊlvz/",ce:"wulvz",sounds:5,enDef:"Plural of wolf.",jpWord:"オオカミ（複数）",jpDef:"オオカミの複数形",soundFile:"audio/wolves.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"woman",cefr:"A1",ipa:"/ˈwʊm.ən/",ce:"wum-un",sounds:4,enDef:"An adult female human.",jpWord:"女性",jpDef:"大人の女性",soundFile:"audio/woman.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"women",cefr:"A1",ipa:"/ˈwɪm.ɪn/",ce:"wim-in",sounds:4,enDef:"Plural of woman.",jpWord:"女性たち",jpDef:"女性の複数形",soundFile:"audio/women.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"wood",cefr:"A1",ipa:"/wʊd/",ce:"wud",sounds:3,enDef:"Material from trees.",jpWord:"木材",jpDef:"木からできた材料",soundFile:"audio/wood.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"would",cefr:"A1",ipa:"/wʊd/",ce:"wud",sounds:3,enDef:"Past or conditional form of will.",jpWord:"〜だろう／〜したい",jpDef:"仮定や丁寧表現",soundFile:"audio/would.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"wrist",cefr:"A2",ipa:"/rɪst/",ce:"rist",sounds:4,enDef:"The joint between hand and arm.",jpWord:"手首",jpDef:"手と腕の間の関節",soundFile:"audio/wrist.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"write",cefr:"A1",ipa:"/raɪt/",ce:"rait",sounds:3,enDef:"To form letters or words.",jpWord:"書く",jpDef:"文字を書く",soundFile:"audio/write.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"wrong",cefr:"A1",ipa:"/rɔːŋ/",ce:"rawng",sounds:4,enDef:"Not correct.",jpWord:"間違った",jpDef:"正しくない",soundFile:"audio/wrong.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"xenon",cefr:"C1",ipa:"/ˈziː.nɒn/",ce:"zee-non",sounds:5,enDef:"A chemical element, a noble gas.",jpWord:"キセノン",jpDef:"希ガスの一種",soundFile:"audio/xenon.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"xylophone",cefr:"B2",ipa:"/ˈzaɪ.lə.foʊn/",ce:"zai-luh-fone",sounds:9,enDef:"A musical instrument with wooden bars.",jpWord:"木琴",jpDef:"木の板を叩く楽器",soundFile:"audio/xylophone.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"yacht",cefr:"B2",ipa:"/jɒt/",ce:"yot",sounds:2,enDef:"A large boat used for pleasure.",jpWord:"ヨット",jpDef:"娯楽用の船",soundFile:"audio/yacht.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"yard",cefr:"A1",ipa:"/jɑːrd/",ce:"yard",sounds:3,enDef:"An outdoor area next to a house.",jpWord:"庭",jpDef:"家の外の敷地",soundFile:"audio/yard.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"yellow",cefr:"A1",ipa:"/ˈjel.oʊ/",ce:"yel-oh",sounds:5,enDef:"A bright color like the sun.",jpWord:"黄色",jpDef:"太陽のような色",soundFile:"audio/yellow.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"yeoman",cefr:"C1",ipa:"/ˈjoʊ.mən/",ce:"yo-man",sounds:4,enDef:"A historically free farmer or attendant.",jpWord:"自由農民",jpDef:"歴史的な小地主",soundFile:"audio/yeoman.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"yes",cefr:"A1",ipa:"/jes/",ce:"yes",sounds:3,enDef:"Used to express agreement.",jpWord:"はい",jpDef:"同意を表す言葉",soundFile:"audio/yes.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"yolk",cefr:"B1",ipa:"/joʊk/",ce:"yoke",sounds:2,enDef:"The yellow part of an egg.",jpWord:"卵黄",jpDef:"卵の黄色い部分",soundFile:"audio/yolk.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"zoo",cefr:"A1",ipa:"/zuː/",ce:"zoo",sounds:1,enDef:"A place where animals are kept.",jpWord:"動物園",jpDef:"動物を飼育・展示する場所",soundFile:"audio/zoo.mp3",tallies:{hard:0,skip:0,easy:0}},

{word:"pal",cefr:"A1",ipa:"/pæl/",ce:"pal",sounds:1, enDef:"Informal: a friend or buddy.",jpWord:"友達",jpDef:"友人・仲間", soundFile:"audio/pal.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"shall",cefr:"B2",ipa:"/ʃæl/",ce:"shal",sounds:1, enDef:"Modal verb used to express future tense or formal obligation.",jpWord:"〜だろう／〜すべき",jpDef:"未来や義務・決意を表す助動詞", soundFile:"audio/shall.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"any",cefr:"A1",ipa:"/ˈeni/",ce:"any",sounds:2, enDef:"Used to refer to one or some of a thing or number of things regardless of amount or number.",jpWord:"どの〜でも",jpDef:"どれでも・いくらでも", soundFile:"audio/any.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"said",cefr:"A1",ipa:"/sɛd/",ce:"sed",sounds:1, enDef:"Past tense of <em>say</em>, meaning to have spoken or expressed in words.",jpWord:"言った",jpDef:"話した", soundFile:"audio/said.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"cause",cefr:"B1",ipa:"/kɔːz/",ce:"kawz",sounds:1, enDef:"A reason why something happens; something that brings about an effect.",jpWord:"原因",jpDef:"出来事の原因・理由", soundFile:"audio/cause.mp3",tallies:{hard:0,skip:0,easy:0}},

{word:"is",cefr:"A1",ipa:"/ɪz/",ce:"iz",sounds:1,enDef:"The present form of 'be', used to describe or identify.",jpWord:"です",jpDef:"〜である・〜です",soundFile:"audio/is.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"a",cefr:"A1",ipa:"/ə/",ce:"uh",sounds:1,enDef:"One; used before a singular noun.",jpWord:"一つの",jpDef:"不特定の一つ",soundFile:"audio/a.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"peach",cefr:"A1",ipa:"/piːtʃ/",ce:"peech",sounds:1,enDef:"A sweet, soft, round fruit.",jpWord:"桃",jpDef:"甘くて柔らかい果物",soundFile:"audio/peach.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"at",cefr:"A1",ipa:"/æt/",ce:"at",sounds:1,enDef:"Used to show a place or position.",jpWord:"〜で",jpDef:"場所や位置を表す",soundFile:"audio/at.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"the",cefr:"A1",ipa:"/ðə/",ce:"thuh",sounds:1,enDef:"Used before a noun to show something specific.",jpWord:"その",jpDef:"特定のものを示す",soundFile:"audio/the.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"pink",cefr:"A1",ipa:"/pɪŋk/",ce:"pingk",sounds:1,enDef:"A light red color.",jpWord:"ピンク",jpDef:"薄い赤色",soundFile:"audio/pink.mp3",tallies:{hard:0,skip:0,easy:0}},
{word:"big",cefr:"A1",ipa:"/bɪɡ/",ce:"big",sounds:1,enDef:"Large in size.",jpWord:"大きい",jpDef:"サイズが大きい",soundFile:"audio/big.mp3",tallies:{hard:0,skip:0,easy:0}},


];

